from sentence_transformers import SentenceTransformer
import torch

california_policy_topics = [
    "K-12 school finance teacher retention student performance education equity",
    "California public universities tuition affordability financial aid access higher education funding",
    "Career technical education workforce training vocational pathways job readiness programs",
    "Affordable housing development zoning density bonus housing supply homelessness prevention",
    "Tenant rights eviction protections rent control rental housing affordability",
    "Homelessness supportive housing unhoused populations shelter access wraparound services",
    "Water rights drought management agricultural water use groundwater sustainability urban conservation",
    "Wildfire prevention forest management defensible space fire suppression vegetation clearance",
    "Electricity grid reliability utility regulation wildfire liability renewable energy integration",
    "Decarbonization energy efficiency building electrification appliance standards clean energy transition",
    "Air quality emissions standards pollution control disadvantaged community mitigation",
    "Climate adaptation sea level rise coastal resilience flood control urban heat islands",
    "Public transit infrastructure rail expansion zero emission buses traffic congestion reduction",
    "Highways road maintenance state infrastructure funding transportation improvement projects",
    "Broadband internet access rural connectivity digital equity infrastructure deployment grants",
    "Mental health services crisis intervention psychiatric care Medi-Cal behavioral health",
    "Substance use disorder harm reduction opioid treatment fentanyl prevention drug diversion",
    "Child welfare foster care adoption permanency social worker caseload family reunification",
    "Elder care long term services IHSS caregiver workforce nursing home oversight",
    "Disability rights accessibility independent living ADA compliance supportive services",
    "Healthcare access Medi-Cal managed care provider reimbursement hospital funding",
    "Public health disease control immunizations pandemic preparedness local health departments",
    "Food insecurity CalFresh food banks nutrition assistance hunger prevention programs",
    "Environmental justice pollution burdens cumulative impacts disadvantaged community protections",
    "Water pollution stormwater runoff drinking water contaminants safe clean supply",
    "Agricultural regulation pesticide use farmworker protections sustainable agriculture soil conservation",
    "Coastal protection shoreline preservation habitat restoration ocean pollution prevention",
    "Parks and public lands recreation trail access conservation funding habitat protection",
    "Criminal justice reform sentencing reduction probation diversion incarceration alternatives",
    "Police accountability body cameras use of force civilian oversight public trust",
    "Firearm regulation background checks red flag laws gun violence prevention",
    "Emergency management disaster response wildfire preparedness flood recovery coordination",
    "Human trafficking prevention victim services law enforcement anti-trafficking task forces",
    "Budget reserves rainy day fund fiscal stabilization bond debt management",
    "Local government finance property taxes redevelopment agencies municipal fiscal health",
    "State tax policy corporate taxes income taxes sales tax exemptions revenue generation",
    "Cannabis regulation retail licensing cultivation taxation youth access prevention",
    "Insurance oversight consumer protection health auto homeowner premium rate review",
    "Small business development regulatory relief entrepreneurship minority business enterprise support",
    "Technology regulation consumer privacy data security artificial intelligence algorithmic accountability",
    "Campaign finance disclosure independent expenditures lobbying ethics political transparency",
    "Voting rights election security voter registration mail ballot access ranked choice voting",
    "Government transparency public records Brown Act open meetings whistleblower protections",
    "Immigration protections undocumented residents sanctuary policies deportation defense",
    "Gender equity reproductive rights workplace discrimination equal pay parental leave",
    "LGBTQ+ rights transgender protections school inclusion hate crimes prevention",
    "Racial equity anti-discrimination restorative justice inclusive education curriculum reform",
    "Veterans services housing benefits employment reintegration mental health supports",
    "Labor rights minimum wage wage theft enforcement collective bargaining workplace safety",
    "Paid leave family leave sick leave medical leave small business impacts",
    "Workforce development apprenticeships job training reskilling economic mobility programs",
    "State employee pensions public retirement systems CalPERS benefit reform",
    "Public transportation safety accessibility fare affordability low income rider assistance",
    "Affordable childcare early learning preschool provider workforce child development programs",
    "Consumer protection financial scams fraud prevention debt collection predatory lending",
    "Housing discrimination fair housing enforcement zoning segregation equitable development",
    "Wildlife conservation endangered species habitat preservation biodiversity protection programs",
    "Renewable energy solar net metering wind energy grid integration clean power",
    "Natural gas regulation methane emissions infrastructure safety gas appliance standards",
    "Vehicle emissions zero emission vehicle incentives smog checks air pollution",
    "Oil drilling fracking regulation offshore oil platform decommissioning environmental safety",
    "Tribal affairs land sovereignty gaming compacts economic development native representation",
    "Military and veterans affairs state military department national guard emergency response",
    "COVID-19 pandemic response public health emergency vaccination testing mitigation efforts",
    "State information technology cybersecurity modernization digital services user access equity",
    "Corrections prison population rehabilitation reentry parole community supervision",
    "Child support enforcement family court collections paternity establishment financial obligations",
    "Public libraries literacy programs broadband access educational resources community hubs",
    "Utilities oversight CPUC rate setting electricity gas telecommunications public accountability",
    "Economic development regional investment job creation economic stimulus small business loans",
    "Public employee relations collective bargaining strikes grievance arbitration workforce disputes",
    "Mobile home rent stabilization manufactured housing tenant protections park regulations",
    "Short term rental regulation vacation housing zoning neighborhood impacts tourist displacement",
    "Public utility wildfire mitigation vegetation management electrical infrastructure safety plans",
    "Energy storage battery incentive programs peak load management renewable energy integration",
    "Water recycling wastewater reuse potable reuse treatment groundwater replenishment",
    "Urban heat island mitigation tree canopy expansion cool pavements building codes",
    "Stormwater capture green infrastructure runoff management urban flood prevention",
    "Salton Sea restoration air quality dust mitigation habitat conservation regional collaboration",
    "Public employee health benefits bargaining premium contributions retiree medical obligations",
    "State procurement diversity small business disadvantaged business enterprise contracting goals",
    "Correctional officer labor relations staffing levels overtime prison safety workplace rights",
    "Traffic enforcement automated speed cameras red light violations pedestrian safety programs",
    "Public charter school accountability fiscal oversight renewal and revocation standards",
    "Ethnic studies curriculum implementation graduation requirement culturally responsive pedagogy",
    "Library construction bond funding capital outlay public library infrastructure modernization",
    "Toxic chemical disclosure Proposition 65 safe harbor levels consumer product safety",
    "Warehouse labor standards workplace quotas ergonomic protections injury prevention policies",
    "Gig economy worker classification independent contractor disputes AB 5 exemptions",
    "Flood control levee maintenance state-federal project funding Delta and Central Valley protection",
    "Unclaimed property escheatment holder compliance reunification outreach owner claims process",
    "Alcohol beverage control licensing tied house restrictions responsible beverage service training",
    "Youth diversion programs juvenile delinquency prevention community-based alternatives criminal penalties",
    "Sexual harassment prevention workplace training employer liability legal compliance",
    "Unemployment insurance trust fund solvency employer tax rates benefit payment delays",
    "Sea level rise adaptation coastal erosion infrastructure relocation living shoreline projects"
]

# model = SentenceTransformer('all-MiniLM-L6-v2')
# policy_embeddings = model.encode(california_policy_topics, convert_to_tensor=True, normalize_embeddings=True, batch_size=32, show_progress_bar=True)
# torch.save(policy_embeddings, 'policy_embeddings.pt')

print(len(torch.load('policy_embeddings.pt')))