from sentence_transformers import SentenceTransformer
import torch

california_policy_topics = [
    "K-12 elementary school middle school high school public teacher student education",
    "public universities higher education",
    "career technical workforce training vocational job readiness",
    "affordable housing development zoning",
    "tenant rights eviction rent control renters protections",
    "homelessness supportive housing unhoused populations",
    "water drought management agricultural groundwater",
    "wildfire prevention forest management",
    "electricity grid utility renewable energy",
    "decarbonization energy efficiency clean energy",
    "air quality emissions pollution",
    "climate adaptation sea level rise coastal resilience flood control urban heat islands",
    "public transit infrastructure rail expansion zero emission buses traffic congestion reduction",
    "highway road maintenance infrastructure state transportation improvement funding",
    "broadband internet access rural connectivity digital equity infrastructure deployment grants",
    "mental health services crisis intervention psychiatric care Medi-Cal behavioral health",
    "substance use disorder harm reduction opioid treatment fentanyl prevention drug diversion",
    "child welfare foster care adoption permanency social worker caseload family reunification",
    "elder care long term services IHSS caregiver workforce nursing home oversight",
    "disability rights accessibility independent living ADA compliance supportive services",
    "healthcare access Medi-Cal managed care provider reimbursement hospital funding",
    "public health disease control immunizations pandemic preparedness local health departments",
    "food insecurity CalFresh food banks nutrition assistance hunger prevention programs",
    "environmental justice pollution burdens cumulative impacts disadvantaged community protections",
    "water pollution stormwater runoff drinking water contaminants safe clean supply",
    "agriculture regulation pesticide use farmworker protections sustainable agriculture soil conservation",
    "coastal protection shoreline preservation habitat restoration ocean pollution prevention",
    "parks public lands recreation trail access conservation funding habitat protection",
    "criminal justice reform sentencing probation diversion incarceration alternatives",
    "police accountability body cameras use of force civilian oversight public trust",
    "firearm regulation background checks red flag laws gun violence prevention",
    "emergency management disaster response wildfire preparedness flood recovery coordination",
    "human trafficking prevention victim services law enforcement anti-trafficking task forces",
    "budget reserves rainy day fund fiscal stabilization bond debt management",
    "local government finance property taxes redevelopment municipal fiscal health",
    "state tax policy corporate income sales tax exemptions revenue generation",
    "cannabis regulation retail licensing cultivation taxation youth access prevention",
    "insurance oversight consumer protection health auto homeowner premium review",
    "small business development regulatory relief entrepreneurship minority enterprise support",
    "technology regulation consumer privacy data security artificial intelligence accountability",
    "campaign finance disclosure independent expenditures lobbying ethics transparency",
    "voting rights election security voter registration mail ballot ranked choice",
    "government transparency public records open meetings whistleblower protections Brown Act",
    "immigration protections undocumented residents sanctuary policies deportation defense",
    "gender equity reproductive rights workplace discrimination equal pay parental leave",
    "LGBTQ rights transgender protections school inclusion hate crimes prevention",
    "racial equity anti-discrimination restorative justice inclusive education curriculum",
    "veterans services housing benefits employment reintegration mental health support",
    "labor rights minimum wage wage theft collective bargaining workplace safety",
    "paid leave family sick medical leave small business policy impacts",
    "workforce development apprenticeships job training reskilling economic mobility programs",
    "state employee pensions retirement systems CalPERS benefit reform fiscal stability",
    "public transit safety accessibility fare affordability low income rider assistance",
    "affordable childcare early learning preschool provider workforce development programs",
    "consumer protection financial scams fraud prevention debt collection predatory lending",
    "housing discrimination fair housing enforcement zoning segregation equitable development",
    "wildlife conservation endangered species habitat preservation biodiversity protection programs",
    "renewable energy solar net metering wind energy grid integration clean power",
    "natural gas regulation methane emissions pipeline safety appliance standards",
    "vehicle emissions zero emission vehicle incentives smog checks air pollution",
    "oil drilling fracking regulation offshore oil platform decommissioning safety",
    "tribal affairs land sovereignty gaming compacts economic development native representation",
    "military veterans affairs national guard state military emergency response",
    "covid-19 pandemic response public health emergency vaccination testing mitigation",
    "state information technology cybersecurity modernization digital services access equity",
    "corrections prison population rehabilitation reentry parole community supervision",
    "child support enforcement family court collections paternity establishment financial obligations",
    "public libraries literacy programs broadband access educational resources community hubs",
    "utilities oversight CPUC rate setting electricity gas telecommunications accountability",
    "economic development regional investment job creation stimulus small business loans",
    "public employee relations collective bargaining strikes arbitration workplace disputes",
    "mobile home rent stabilization manufactured housing tenant protections park regulations",
    "short term rental regulation vacation housing zoning neighborhood impacts tourism",
    "public utility wildfire mitigation vegetation management electrical infrastructure safety",
    "energy storage battery incentive programs peak load management renewable integration",
    "water recycling wastewater reuse potable reuse treatment groundwater replenishment",
    "urban heat mitigation tree canopy expansion cool pavements building codes",
    "stormwater capture green infrastructure runoff management flood prevention",
    "salton sea restoration air quality dust mitigation habitat conservation",
    "public employee health benefits bargaining premium contributions retiree obligations",
    "state procurement diversity small disadvantaged business contracting goals",
    "correctional officer labor relations staffing overtime prison workplace rights",
    "traffic enforcement automated speed cameras red light pedestrian safety",
    "charter school accountability fiscal oversight renewal revocation standards",
    "ethnic studies curriculum implementation graduation requirement culturally responsive pedagogy",
    "library construction bond funding capital outlay infrastructure modernization",
    "toxic chemical disclosure Proposition 65 safe harbor consumer product safety",
    "warehouse labor standards workplace quotas ergonomic protections injury prevention",
    "gig economy worker classification independent contractor disputes AB5 exemptions",
    "flood control levee maintenance state federal project funding Delta protection",
    "unclaimed property escheatment holder compliance reunification outreach claims process",
    "alcohol beverage control licensing tied house restrictions responsible service training",
    "youth diversion juvenile delinquency prevention community alternatives criminal penalties",
    "sexual harassment prevention workplace training employer liability legal compliance",
    "unemployment insurance trust fund solvency employer tax rates benefit delays",
    "sea level rise adaptation coastal erosion infrastructure relocation shoreline projects"
]

model = SentenceTransformer('all-MiniLM-L6-v2')
policy_embeddings = model.encode(california_policy_topics, convert_to_tensor=True, normalize_embeddings=True, batch_size=32, show_progress_bar=True)
torch.save(policy_embeddings, 'policy_embeddings.pt')